Fix[worked on caching specific BPP data to cache db and filtering based on eligibility criteria]
PSMRI/beneficiary-backend pull request #41
Opened 2024-11-20 13:18 UTC by Dhanashree-Patil95

## 📋 Description

JIRA ID: 

Please provide a summary of the change and the motivation behind it. Include relevant context and details.

---

## ✅ Type of Change

- [ ] 🐞 **Bug fix** (non-breaking change which resolves an issue)
- [ ] ✨ **New feature** (non-breaking change which adds functionality)
- [ ] 🔥 **Breaking change** (fix or feature that would cause existing functionality to not work as expected)
- [ ] 🛠 **Refactor** (change that is neither a fix nor a new feature)
- [ ] ⚙️ **Config change** (configuration file or build script updates)
- [ ] 📚 **Documentation** (updates to docs or readme)
- [ ] 🧪 **Tests** (adding new or updating existing tests)
- [ ] 🎨 **UI/UX** (changes that affect the user interface)
- [ ] 🚀 **Performance** (improves performance)
- [ ] 🧹 **Chore** (miscellaneous changes that don't modify src or test files)

---

## ℹ️ Additional Information

Please describe how the changes were tested, and include any relevant screenshots, logs, or other information that provides additional context.

2024-11-20 15:48 UTC, GitVivekHub requested changes

2024-11-20 15:48 UTC, GitVivekHub commented on src/services/hasura/hasura.service.ts
> +        matches = job.title?.toLowerCase().includes(search.toLowerCase());
@Dhanashree-Patil95 please add extra ? check here

2024-11-21 04:31 UTC, Dhanashree-Patil95 commented on src/services/hasura/hasura.service.ts
> +        matches = job.title?.toLowerCase().includes(search.toLowerCase());
resolved

2024-11-21 04:48 UTC, GitVivekHub approved these changes

2024-11-21 04:50 UTC, merged